baseURL = "https://www.ec2mssqlworkshop.com/"
languageCode = "en-us"
title = "MS-SQL Server Workshop"
theme = "hugo-theme-learn"
sectionPagesMenu = "main"
pygmentsCodeFences = true

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  showVisitedLinks = true
  description = "MS-SQL Server Workshop"
  disableSearch = false
  disableAssetsBusting = false
  disableLanguageSwitchingButton = true
  disableShortcutsTitle = false

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false


[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Windows on AWS"
url = "https://aws.amazon.com/windows/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Feedback / Questions?"
url = "mailto:mssql-workshop-feedback@amazon.com"
weight = 30
